server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.65:1521:orcl
    username: member
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true